version: "3"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - './rh_db/:/var/lib/mysql'

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080


  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - './rh_caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './rh_front/dist/:/srv'

  backend:
    container_name: backend
    build: 
      context: ./rh_backend/
      dockerfile: Dockerfile
    ports:
      - "3300:3300"