version: "3"

services:

  backend:
    container_name: backend
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "3300:3300"


  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - './caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './front/:/srv'


  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - './db/:/var/lib/mysql'


  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
