version: "3"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: root2
      MYSQL_PASSWORD: root
    volumes:
      - './rh_db/:/var/lib/mysql'

  adminer:
    image: adminer
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 8081:8080

  backend:
    container_name: backend
    depends_on:
      - db
    build: 
      context: ./rh_back/
      dockerfile: Dockerfile
    volumes:
      - './rh_back/:/var/www/app'
    ports:
      - 3300:3300

  front:
    container_name: frontend
    depends_on:
      - backend
    build: 
      context: ./rh_front/
      dockerfile: Dockerfile
    ports:
      - 8001:80

  caddy:
    image: caddy:latest
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - './rh_caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './rh_front/dist/:/srv'